name: Compile Android APK

on:
  push:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libstdc++6 make
        pip install --upgrade pip
        pip install --user --upgrade buildozer cython==0.29.36

    - name: Accept Android SDK Licenses
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
        echo -e "\n24333f8a43b681623ef0eb379f5d254f48383f38" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" >> ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
        echo -e "\nd56f5187479451eabf01fb78af6dfcb131a648af" >> ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license

    - name: Run Buildozer
      run: |
        export PATH=$PATH:~/.local/bin
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
