name: Compile Android APK

on:
  push:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 40

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Clean Cache and Setup Environment
      run: |
        rm -rf ~/.buildozer
        rm -rf .buildozer

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libstdc++6 make

    - name: Install Buildozer and Cython
      run: |
        pip install --upgrade pip
        pip install --user --upgrade buildozer cython==0.29.36

    - name: Run Buildozer
      env:
        ANDROID_SDK_ACCEPT_LICENSE: "1"
        BUILDER_DEBUG: "1"
      run: |
        export PATH=$PATH:~/.local/bin
        yes | buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: package
        path: bin/*.apk
